services:
  devcontainer:
    build:
      context: ./.devcontainer
      dockerfile: Dockerfile
    container_name: devcontainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - node_modules_volume:/workspace/frontend/node_modules
      - vendor_volume:/workspace/backend/vendor
      - .:/workspace
    networks:
      - common
    stdin_open: true
    tty: true

networks:
  common:
    driver: bridge

volumes:
  node_modules_volume:
  vendor_volume: