version: '4.1'
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: appdb
    ports:
      - "5432:5432"
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/workspace
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: tail -f /dev/null
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    depends_on:
      - web
