apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
      role: database
  template:
    metadata:
      name: mysql
      labels:
        app: wordpress
        role: database
    spec:
      containers:
      - name: mysql
        image: mysql
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: password
          - name: MYSQL_DATABASE
            value: wordpress
          - name: MYSQL_USER
            value: wordpress_user
          - name: MYSQL_PASSWORD
            value: wordpress_pass
        ports:
          - containerPort: 3306